name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build packages
        run: |
          yarn workspace @healthify/ui-kit build
          yarn workspace @healthify/fhir-server build
          yarn workspace @healthify/db build
      
      - name: Build patient portal
        run: yarn workspace @healthify/patient-portal build
      
      - name: Build doctor portal
        run: yarn workspace @healthify/doctor-portal build
      
      - name: Build admin portal
        run: yarn workspace @healthify/admin-portal build 